import { useMemo, useState } from 'react'
import { SettingType } from '../utils/enums'
import { EditSetting, EditSettingValueTypes } from '../utils/interfaces'
import { useAllAirflows } from '../utils/queries'
import Button from './Button'
import ConfirmationModal from './ConfirmationModal'
import TableInputFields from '../utils/TableInputFields'
import RequiredFieldsInfo from './RequiredFieldsInfo'
import './Modals.scss'

interface CreateAirflowModalProps {
  type: string
  onSave: (newTableData: EditSetting[]) => void
  onClose: () => void
}

function initialCreateAirflowSettings(airflowType: string) {
  let settings: EditSetting[] = []
  if (airflowType === 'import') {
    settings = [
      { label: 'DAG Name', value: null, type: SettingType.Text }, //Free-text, varchar(64), have to be unique across import, export and custom, required
      { label: 'Schedule Interval', value: null, type: SettingType.Text }, // Free-text, Time to execute DAG, varchar(128), required
      // {
      //   label: '',
      //   value: '',
      //   type: SettingType.GroupingSpace
      // }, // Layout space
      {
        label: 'Auto Regenerate DAG',
        value: true,
        type: SettingType.Boolean
      }, // Boolean, if not set pre-set default value: true, true = The DAG will be auto regenerated by manage command, required
      {
        label: 'Filter Table',
        value: null,
        type: SettingType.Text
      } // Free-text, varchar(16384), Filter string for database and table. ; separated. Wildcards (*) allowed. Example HIVE_DB.HIVE_TABLE; HIVE_DB.HIVE_TABLE, required
    ]
  }
  return settings
}

function CreateAirflowModal({
  type,
  onSave,
  onClose
}: CreateAirflowModalProps) {
  const settings = initialCreateAirflowSettings(type)
  const { data: airflowsData } = useAllAirflows()
  const airflowNames = useMemo(
    () =>
      Array.isArray(airflowsData)
        ? airflowsData.map((airflow) => airflow.name)
        : [],
    [airflowsData]
  )
  console.log('airflowNames', airflowNames)

  const [editedSettings, setEditedSettings] = useState<EditSetting[]>(settings)
  const [hasChanges, setHasChanges] = useState(false)
  const [showConfirmation, setShowConfirmation] = useState(false)

  const isRequiredFieldEmpty = useMemo(() => {
    const requiredLabels = ['DAG Name']
    return editedSettings.some(
      (setting) => requiredLabels.includes(setting.label) && !setting.value
    )
  }, [editedSettings])

  const handleInputChange = (
    index: number,
    newValue: EditSettingValueTypes | null
  ) => {
    if (index < 0 || index >= editedSettings.length) {
      console.warn(`Invalid index: ${index}`)
      return
    }

    const updatedSettings = editedSettings?.map((setting, i) =>
      i === index ? { ...setting, value: newValue } : setting
    )

    setEditedSettings(updatedSettings)
    setHasChanges(true)
  }

  const handleSelect = (
    item: EditSettingValueTypes | null,
    keyLabel?: string
  ) => {
    const index = editedSettings.findIndex(
      (setting) => setting.label === keyLabel
    )
    if (index !== -1) {
      handleInputChange(index, item)
    }
  }

  const handleSave = () => {
    const newTableSettings = settings.map((setting) => {
      const editedSetting = editedSettings.find(
        (es) => es.label === setting.label
      )

      return editedSetting ? { ...setting, ...editedSetting } : { ...setting }
    })

    onSave(newTableSettings)
    onClose()
  }

  const handleCancelClick = () => {
    if (hasChanges) {
      setShowConfirmation(true)
    } else {
      onClose()
    }
  }

  const handleConfirmCancel = () => {
    setShowConfirmation(false)
    onClose()
  }

  const handleCloseConfirmation = () => {
    setShowConfirmation(false)
  }

  return (
    <div className="table-modal-backdrop">
      <div className="table-modal-content">
        <h2 className="table-modal-h2">Create DAG</h2>
        <form
          onSubmit={(event) => {
            event.preventDefault()
            handleSave()
          }}
        >
          <div className="table-modal-body">
            {editedSettings &&
              editedSettings.map((setting, index) => (
                <div key={index} className="table-modal-setting">
                  <TableInputFields
                    index={index}
                    setting={setting}
                    handleInputChange={handleInputChange}
                    handleSelect={handleSelect}
                  />
                </div>
              ))}
          </div>
          <RequiredFieldsInfo isRequiredFieldEmpty={isRequiredFieldEmpty} />

          <div className="table-modal-footer">
            <Button
              title="Cancel"
              onClick={handleCancelClick}
              lightStyle={true}
            />
            <Button type="submit" title="Save" />
          </div>
        </form>
      </div>
      {showConfirmation && (
        <ConfirmationModal
          onConfirm={handleConfirmCancel}
          onCancel={handleCloseConfirmation}
          message="Any unsaved changes will be lost."
        />
      )}
    </div>
  )
}

export default CreateAirflowModal
